### ISSUE TITLE
Using this in a controller

### ISSUE THREAD

**Issue by doodirock** [ckatzorke/angular-giantbomb#1]
Do you have any examples of how to use this wrapper in a controller.  I can't seem to get this to work.

**Comment by ckatzorke** [comment]
Nice to see some interest in this.The project is quite old, but have you chekced https://github.com/ckatzorke/gamebomb (GameBomb), an (of course) non finished side project, using angular-giantbomb. Additionally, I created another api wrapper, intended to be used server side:
https://github.com/ckatzorke/giantbomb-api (API)
https://github.com/ckatzorke/collect.io-koa (Koa based REST service)
hth

**Comment by doodirock** [comment]
Yep, I'm looking to build out an app using GB, but to be honest i can;t get Angular to play well with JSONP.  I set up my simple service:

```
.factory('GiantFactory', function($resource) {

var base = 'http://www.giantbomb.com/api/search/?format=jsonp&resources=game&api_key=3&query=Legend?callback=JSON_CALLBACK';

return $resource(base, {},
    {
      get: {
        method: 'JSONP'
      }
    }
);
});  
```

However I get an error related to not being JSONP when i fire off get.GiantFactory in my controller.

**Comment by ckatzorke** [comment]
Are you sure it is not just because of the second `?' in your base URL (?callback=JSON_CALLBACK)
After looking at my code (oh my gosh,,,) I changed the search function to using the api/search endpoint and to only parameterize query and api_key (which would make sense since they are dynamic), using a pretty much complete base URI (like in your URL)

```
gameSearch : function(searchString, callback){
            $resource('http://www.giantbomb.com/api/search?resources=game&field_list=name,original_release_date,api_detail_url,site_detail_url&format=jsonp&json_callback=JSON_CALLBACK',
                {
                            query:  searchString,
                  api_key: this._apiKey
                },
                {
                  get: {method: 'JSONP'}
                }).get({}, function(result){
                  callback(result);
                });
            }
```

However, this works fine, but of course changing the ampersand before callback to ? causes an error...

**Comment by doodirock** [comment]
Actually that was a typo sorry!  Sadly the result is the same, each call I'm getting 

```
  Uncaught SyntaxError: Unexpected token :
```

**Comment by doodirock** [comment]
fix.  It didnt like having the format=jsonp param at the beginning of the base url.  That was really odd...  Either way thanks for the direction!

**Comment by ckatzorke** [comment]
Glad to be of any help without actually helping ;-) Good luck
